---

- hosts: all
  become: true
  pre_tasks:

  - name: install updates (Ubuntu)
    tags: always
    apt:
      upgrade: dist
      update_cache: yes
    changed_when: false
    when: ansible_distribution == "Ubuntu"

- hosts: web_servers
  become: true
  tasks:

  - name: install apache and php for Ubuntu servers
    tags: apache,apache2,ubuntu
    apt:
      name: 
        - apache2
        - libapache2-mod-php
      state: latest
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

  - name: copy default_site.html to server 
    tags: apache,apache2
    copy:
      src: default_site.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644

  - name: install unzip
    package:
      name: unzip

  - name: install terraform
    unarchive:
      src: https://releases.hashicorp.com/terraform/1.13.0/terraform_1.13.0_linux_amd64.zip
      dest: /usr/local/bin
      remote_src: yes
      mode: 0755
      owner: root
      group: root

  - name: Modify file and back it up
    lineinfile: 
      path: /home/synology/MYPROJECT/README.PROJECT1
      line: 'this is a brand new line'
      backup: yes

- hosts: all
  become: true
  tasks:

  - name: create cornelius user
    tags: always
    user:
      name: cornelius
      groups: root

  - name: add ssh for cornelius
    tags: always
    authorized_key:
      user: cornelius
      key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIPL7XYZye0qx1EN10dM0+j+0ytvbrxywjl7YtOgkwWV1 ansible"
  - name: add sudoers file for cornelius
    copy:
      src: sudoer_cornelius
      dest: /etc/sudoers.d/cornelius
      owner: root
      group: root
      mode: 0440
